doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            money: App\Shared\Infrastructure\Doctrine\Type\MoneyType
            customer_id: App\Shared\Infrastructure\Doctrine\Type\CustomerIdType
            cart_id: App\Cart\Infrastructure\Doctrine\Type\CartIdType
            cart_item_id: App\Cart\Infrastructure\Doctrine\Type\CartItemIdType
            sku: App\Shared\Infrastructure\Doctrine\Type\SkuType
            qty: App\Shared\Infrastructure\Doctrine\Type\QtyType
            cart_status: App\Cart\Infrastructure\Doctrine\Type\CartStatusType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        controller_resolver:
            auto_mapping: false
        mappings:
            Cart:
                dir: '%kernel.project_dir%/src/Cart/Domain/Entity'
                prefix: 'App\Cart\Domain\Entity'
            Shared:
                dir: '%kernel.project_dir%/src/Shared/Domain/Entity'
                prefix: 'App\Shared\Domain\Entity'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
